"""
Extract weights from TFLite model and generate C header files.
Rename to clean names: w1/w2/w3 for weights, b1/b2/b3 for biases.
"""
import tensorflow as tf
import os, glob

tflite_path = "park_model.tflite"

interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()

details = interpreter.get_tensor_details()

def write_c_array(name, data, filepath):
    with open(filepath, "w") as f:
        f.write(f"// Auto-generated by extract_model.py\n")
        f.write(f"static const float {name}[{len(data)}] = {{\n    ")
        for i, v in enumerate(data):
            f.write(f"{v:.7f}f")
            if i < len(data) - 1:
                f.write(", ")
            if (i + 1) % 8 == 0 and i < len(data) - 1:
                f.write("\n    ")
        f.write("\n};\n")
    print(f"  -> {filepath} ({len(data)} floats)")

# Clean old generated headers
for f in glob.glob("../inc/model_*.h"):
    os.remove(f)

# Collect all tensors
matmul_tensors = {}  # key: layer_name, value: (shape, data)
bias_tensors = {}    # key: layer_name (order), value: data

for d in details:
    name = d["name"]
    idx = d["index"]
    shape = d["shape"]
    try:
        data = interpreter.get_tensor(idx)
    except:
        continue

    flat = data.flatten()
    if len(flat) < 1:
        continue

    print(f"Tensor: {name} shape={list(shape)} len={len(flat)}")

    # Classify: MatMul weight or Bias
    if "MatMul" in name:
        if "dense_2_1" in name:
            matmul_tensors["w3"] = (shape, flat)
        elif "dense_1_2" in name:
            matmul_tensors["w2"] = (shape, flat)
        elif "dense_1" in name:
            matmul_tensors["w1"] = (shape, flat)
    elif "BiasAdd" in name:
        if "dense_2_1" in name:
            bias_tensors["b3"] = flat
        elif "dense_1_2" in name:
            bias_tensors["b2"] = flat
        elif "dense_1" in name:
            bias_tensors["b1"] = flat

# Generate C headers
print("\n=== Generating headers ===")
for key in ["w1", "b1", "w2", "b2", "w3", "b3"]:
    if key in matmul_tensors:
        shape, data = matmul_tensors[key]
        write_c_array(f"model_{key}", data, f"../inc/model_{key}.h")
    elif key in bias_tensors:
        write_c_array(f"model_{key}", bias_tensors[key], f"../inc/model_{key}.h")
    else:
        print(f"  WARNING: {key} not found!")

print("\n=== Model Architecture ===\n"
      "Input(10) -> Dense(16)+ReLU -> Dense(8)+ReLU -> Dense(1) -> Sigmoid\n"
      f"Total params: w1:{len(matmul_tensors.get('w1', [[]])[1])} "
      f"b1:{len(bias_tensors.get('b1', []))} "
      f"w2:{len(matmul_tensors.get('w2', [[]])[1])} "
      f"b2:{len(bias_tensors.get('b2', []))} "
      f"w3:{len(matmul_tensors.get('w3', [[]])[1])} "
      f"b3:{len(bias_tensors.get('b3', []))}")
