"""
车位检测模型训练 + 权重直接导出 C 头文件
输入: 10个连续滤波距离(cm)
输出: 占用概率 (0=空闲 1=占用)
"""
import numpy as np
import tensorflow as tf
import os

# ============ 1. 生成合成训练数据 ============

def gen_occupied(n_samples):
    """有车: 距离 5~45cm, 传感器正对车体"""
    data = []
    for _ in range(n_samples):
        base = np.random.uniform(8, 40)
        seq = base + np.random.randn(10) * 2.0  # ±2cm 噪声
        seq = np.clip(seq, 3, 50)
        data.append(seq)
    return np.array(data, dtype=np.float32)

def gen_free(n_samples):
    """无车: 距离 60~250cm, 传感器对地/无遮挡"""
    data = []
    for _ in range(n_samples):
        base = np.random.uniform(65, 220)
        seq = base + np.random.randn(10) * 8.0  # 更远噪声更大
        seq = np.clip(seq, 55, 300)
        data.append(seq)
    return np.array(data, dtype=np.float32)

def gen_boundary(n_samples):
    """临界状态: 距离 40~65cm, 车在边缘"""
    data = []
    for _ in range(n_samples):
        base = np.random.uniform(42, 58)
        seq = base + np.random.randn(10) * 3.0
        seq = np.clip(seq, 35, 70)
        data.append(seq)
    return np.array(data, dtype=np.float32)

# 生成数据
np.random.seed(42)
n_each = 2000
X_occ = gen_occupied(n_each)
X_free = gen_free(n_each)
X_boundary_occ = gen_boundary(n_each // 4)  # 临界判定为占用
X_boundary_free = gen_boundary(n_each // 4)  # 临界判定为空闲

# 标签: 距离<50cm→占用, ≥50cm→空闲
# 用阈值作为 ground truth（因为超声波检测本身就是这样判断的）
y_occ = np.ones(len(X_occ), dtype=np.float32)
y_free = np.zeros(len(X_free), dtype=np.float32)
y_boundary_occ = np.ones(len(X_boundary_occ), dtype=np.float32)
y_boundary_free = np.zeros(len(X_boundary_free), dtype=np.float32)

X = np.vstack([X_occ, X_free, X_boundary_occ, X_boundary_free])
y = np.hstack([y_occ, y_free, y_boundary_occ, y_boundary_free])

# 打乱
idx = np.random.permutation(len(X))
X, y = X[idx], y[idx]

print(f"训练数据: {len(X)} 样本")
print(f"  占用: {np.sum(y):.0f}, 空闲: {len(y)-np.sum(y):.0f}")
print(f"  占用距离范围: {X[y==1].min():.1f}~{X[y==1].max():.1f} cm")
print(f"  空闲距离范围: {X[y==0].min():.1f}~{X[y==0].max():.1f} cm")

# ============ 2. 构建并训练模型 ============

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(10,)),
    tf.keras.layers.Dense(16, activation='relu',
                          kernel_initializer='he_normal'),
    tf.keras.layers.Dense(8, activation='relu',
                          kernel_initializer='he_normal'),
    tf.keras.layers.Dense(1, activation='sigmoid',
                          kernel_initializer='glorot_uniform')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

print("\n开始训练...")
history = model.fit(X, y, epochs=80, batch_size=32,
                    validation_split=0.15, verbose=1)

# ============ 3. 快速验证 ============

test_cases = [
    ("明显有车 10cm", np.ones(10)*10),
    ("明显有车 20cm", np.ones(10)*20),
    ("明显有车 35cm", np.ones(10)*35),
    ("临界 48cm", np.ones(10)*48),
    ("临界 52cm", np.ones(10)*52),
    ("明显无车 80cm", np.ones(10)*80),
    ("明显无车 150cm", np.ones(10)*150),
    ("明显无车 200cm", np.ones(10)*200),
]

print("\n=== 模型验证 ===")
for name, seq in test_cases:
    prob = model.predict(seq.reshape(1, -1), verbose=0)[0][0]
    bar = "#" * int(prob * 40)
    print(f"  {name:16s} → prob={prob:.4f}  {bar}")

# ============ 4. 导出权重为 C 头文件 ============

out_dir = "../inc"
os.makedirs(out_dir, exist_ok=True)

weights = model.get_weights()
# weights[0]=w1(10,16), [1]=b1(16), [2]=w2(16,8), [3]=b2(8), [4]=w3(8,1), [5]=b3(1)

w1 = weights[0].T.flatten()  # (10,16) → 展平, 行优先 = 每个输出神经元的10个输入权重组
b1 = weights[1].flatten()
w2 = weights[2].T.flatten()  # (16,8) → 展平
b2 = weights[3].flatten()
w3 = weights[4].T.flatten()  # (8,1) → 展平
b3 = weights[5].flatten()

def write_c_array(name, data, filepath):
    with open(filepath, "w", encoding="ascii") as f:
        f.write(f"// Auto-generated by train_model.py\n")
        f.write(f"static const float {name}[{len(data)}] = {{\n    ")
        for i, v in enumerate(data):
            f.write(f"{v:.7f}f")
            if i < len(data) - 1:
                f.write(", ")
            if (i + 1) % 8 == 0 and i < len(data) - 1:
                f.write("\n    ")
        f.write("\n};\n")

write_c_array("model_w1", w1, f"{out_dir}/model_w1.h")
write_c_array("model_b1", b1, f"{out_dir}/model_b1.h")
write_c_array("model_w2", w2, f"{out_dir}/model_w2.h")
write_c_array("model_b2", b2, f"{out_dir}/model_b2.h")
write_c_array("model_w3", w3, f"{out_dir}/model_w3.h")
write_c_array("model_b3", b3, f"{out_dir}/model_b3.h")

print("\n=== 权重已导出 ===")
print(f"  w1: {len(w1)} floats (10x16)")
print(f"  b1: {len(b1)} floats")
print(f"  w2: {len(w2)} floats (16x8)")
print(f"  b2: {len(b2)} floats")
print(f"  w3: {len(w3)} floats (8x1)")
print(f"  b3: {len(b3)} floats")

# 同时保存完整 Keras 模型 (可选)
model.save("park_model.h5")
print("\n模型已保存: park_model.h5")
